# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt6 UI code generator 6.2.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmSettings(object):
    def setupUi(self, frmSettings):
        frmSettings.setObjectName("frmSettings")
        frmSettings.resize(214, 119)
        self.verticalLayout = QtWidgets.QVBoxLayout(frmSettings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblsettings = QtWidgets.QLabel(frmSettings)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblsettings.setFont(font)
        self.lblsettings.setObjectName("lblsettings")
        self.verticalLayout.addWidget(self.lblsettings)
        self.mainlayout = QtWidgets.QGridLayout()
        self.mainlayout.setObjectName("mainlayout")
        self.lblautosave = QtWidgets.QLabel(frmSettings)
        self.lblautosave.setObjectName("lblautosave")
        self.mainlayout.addWidget(self.lblautosave, 2, 0, 1, 1)
        self.lblautoupdate = QtWidgets.QLabel(frmSettings)
        self.lblautoupdate.setObjectName("lblautoupdate")
        self.mainlayout.addWidget(self.lblautoupdate, 0, 0, 1, 1)
        self.chkautosave = QtWidgets.QCheckBox(frmSettings)
        self.chkautosave.setObjectName("chkautosave")
        self.mainlayout.addWidget(self.chkautosave, 2, 1, 1, 1)
        self.chkautoupdate = QtWidgets.QCheckBox(frmSettings)
        self.chkautoupdate.setObjectName("chkautoupdate")
        self.mainlayout.addWidget(self.chkautoupdate, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.mainlayout.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.mainlayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(frmSettings)
        QtCore.QMetaObject.connectSlotsByName(frmSettings)

    def retranslateUi(self, frmSettings):
        _translate = QtCore.QCoreApplication.translate
        frmSettings.setWindowTitle(_translate("frmSettings", "SETTINGS"))
        self.lblsettings.setText(_translate("frmSettings", "SETTINGS"))
        self.lblautosave.setText(_translate("frmSettings", "Auto Save"))
        self.lblautoupdate.setText(_translate("frmSettings", "Auto Update"))
        self.chkautosave.setText(_translate("frmSettings", "CheckBox"))
        self.chkautoupdate.setText(_translate("frmSettings", "CheckBox"))
